/**
 * Interim visuals register.
 *
 * PROJECT RULE: all real art — sprites, tiles, unit icons, buttons, banners,
 * borders, panel chrome — is generated by PixelLab and referenced through the
 * asset manifest. Claude Code does not hand-author final art: no hand-drawn
 * SVG, no CSS gradients or shapes standing in as the finished visual, no
 * procedurally-drawn "good enough" substitute.
 *
 * The one allowance is a clearly interim stopgap so the game is visible while
 * art is being generated — carrying the established palette as flat colour, and
 * the minimum geometry needed to see the board. Everything relying on that
 * allowance MUST be listed here, so it is tracked rather than quietly becoming
 * permanent.
 *
 * Each entry names the manifest key that retires it. A test asserts every
 * `replacedBy` key is actually declared in the manifest, so this list cannot
 * drift into naming art nobody ever queued.
 *
 * TO RETIRE AN ENTRY: generate the asset, drop `pending` from its manifest
 * entry, delete the stopgap code, and remove the row here.
 */

export interface InterimVisual {
  /** Where the stopgap lives. */
  readonly where: string;
  /** What is being faked. */
  readonly what: string;
  /** Manifest key(s) whose generation retires this stopgap. */
  readonly replacedBy: readonly string[];
}

export const INTERIM_VISUALS: readonly InterimVisual[] = [
  {
    where: 'src/ui/MapView.tsx — CastleGlyph',
    what: 'Hand-drawn SVG castle marker. Explicitly a stopgap, not final art.',
    replacedBy: [
      'castle.motteAndBailey',
      'castle.normanKeep',
      'castle.royalCastle',
    ],
  },
  {
    where: 'src/ui/MapView.tsx — ownership hatch patterns',
    what: 'SVG line hatching to distinguish seats without relying on hue alone.',
    replacedBy: ['banner.crimson', 'banner.steel', 'banner.gold', 'banner.verdigris'],
  },
  {
    where: 'src/ui/styles.css — panel chrome',
    what:
      'CSS borders, gradients and the garrison pill, standing in for generated ' +
      'panel frames, buttons and UI chrome.',
    replacedBy: ['ui.panelFrame', 'ui.buttonPrimary', 'ui.scrollHeader'],
  },
  {
    where: 'index.html — no favicon / app icon',
    what:
      'No icon is declared, so browsers request /favicon.ico and get a 404. ' +
      'Left absent deliberately rather than hand-drawing one.',
    replacedBy: ['ui.appIcon'],
  },
  {
    where: 'src/ui/ControlPanel.tsx — resource and faction labels',
    what: 'Text labels where resource icons and faction crests should appear.',
    replacedBy: [
      'resource.wheat',
      'resource.cows',
      'resource.wood',
      'resource.ore',
      'resource.stone',
      'resource.gold',
      'crest.knight',
      'crest.warden',
      'crest.merchant',
      'crest.steward',
    ],
  },
];

/** Every manifest key the interim visuals are waiting on. */
export const awaitedArtKeys = (): string[] =>
  [...new Set(INTERIM_VISUALS.flatMap((v) => v.replacedBy))].sort();
