/**
 * Interim visuals register.
 *
 * PROJECT RULE: all real art — sprites, tiles, unit icons, buttons, banners,
 * borders, panel chrome — is generated by PixelLab and referenced through the
 * asset manifest. Claude Code does not hand-author final art: no hand-drawn
 * SVG, no CSS gradients or shapes standing in as the finished visual, no
 * procedurally-drawn "good enough" substitute.
 *
 * The one allowance is a clearly interim stopgap so the game is visible while
 * art is being generated — carrying the established palette as flat colour, and
 * the minimum geometry needed to see the board. Everything relying on that
 * allowance MUST be listed here, so it is tracked rather than quietly becoming
 * permanent.
 *
 * Each entry names the manifest key that retires it. A test asserts every
 * `replacedBy` key is actually declared in the manifest, so this list cannot
 * drift into naming art nobody ever queued.
 *
 * TO RETIRE AN ENTRY: generate the asset, drop `pending` from its manifest
 * entry, delete the stopgap code, and remove the row here.
 */

export interface InterimVisual {
  /** Where the stopgap lives. */
  readonly where: string;
  /** What is being faked. */
  readonly what: string;
  /** Manifest key(s) whose generation retires this stopgap. */
  readonly replacedBy: readonly string[];
}

export const INTERIM_VISUALS: readonly InterimVisual[] = [
  {
    where: 'src/ui/MapView.tsx — season-less terrain tiles',
    what:
      'The single terrain set is drawn in every season. Correct art swaps the ' +
      'whole palette per season, including the grain growth cycle.',
    replacedBy: [
      'terrain.open.spring',
      'terrain.open.summer',
      'terrain.open.autumn',
      'terrain.open.winter',
    ],
  },
  {
    where: 'src/ui/styles.css — .ov-top, .ov-strip, .ov-health, .ov-corner',
    what:
      'The overhead county screen\'s chrome is flat CSS: the top bar, the ' +
      'county strip, the health thermometer and the minimap surround. The ' +
      'readouts inside them are real generated art; the frames around them ' +
      'are not.',
    replacedBy: ['ui.panelFrame', 'ui.buttonPrimary'],
  },
  {
    where: 'src/ui/county/Minimap.tsx — flat polygon fills',
    what:
      'County shapes are drawn as flat SVG polygons in seat colours. The spec ' +
      'asks for shape and ownership only at this scale, so this may well be ' +
      'the finished answer — it is listed so that is a decision someone makes ' +
      'rather than one that happens by default.',
    replacedBy: ['ui.panelFrame'],
  },
  {
    where: 'src/ui/styles.css — panel chrome',
    what:
      'CSS borders, gradients and the garrison pill, standing in for generated ' +
      'panel frames, buttons and UI chrome.',
    replacedBy: ['ui.panelFrame', 'ui.buttonPrimary', 'ui.scrollHeader'],
  },
];

/**
 * Deliberately NOT in the register:
 *
 *  - The terrain tint fill and the per-seat ownership hatching in MapView.
 *    Neither stands in for art. The tint is error handling for a manifest
 *    entry that will not resolve, and the hatching is an accessibility
 *    affordance so ownership survives colour-blindness and greyscale — a
 *    banner sprite cannot do that job, so generating banners does not retire
 *    it.
 *
 *  - The generated UI kit sheets (ui.kit.*). Those are real art, but each is a
 *    sheet of many components rather than a usable frame, so the sliced
 *    entries they feed (ui.panelFrame and friends) stay pending until someone
 *    cuts them. The CSS panel chrome above is what stands in meanwhile.
 */

/** Every manifest key the interim visuals are waiting on. */
export const awaitedArtKeys = (): string[] =>
  [...new Set(INTERIM_VISUALS.flatMap((v) => v.replacedBy))].sort();

/**
 * Art queued for a surface that does not exist yet.
 *
 * A pending key with nothing waiting on it is usually a mistake — art ordered
 * for no reason. But art legitimately gets queued ahead of the screen that will
 * use it, and the alternative to naming that is an ever-widening allowlist that
 * eventually asserts nothing.
 *
 * So each planned group states WHAT will consume it. When that surface ships,
 * the group moves into INTERIM_VISUALS (if a stopgap stands in meanwhile) or is
 * deleted outright.
 */
export interface PlannedArt {
  /** The surface that will consume these. */
  readonly forSurface: string;
  readonly keyPrefixes: readonly string[];
}

export const PLANNED_ART: readonly PlannedArt[] = [
  {
    // Generated while building the county map, then taken back off it: the
    // knight belongs in a shop window, not standing in a field. Kept rather
    // than deleted because both screens are specced around a picture of the
    // goods with a quantity control beside it.
    forSurface: 'Blacksmith/armory and merchant shop screens — pictures of the goods',
    keyPrefixes: ['equipment.'],
  },
  {
    forSurface: 'County screen — field tiles, industry sites and on-map sprites',
    keyPrefixes: ['field.', 'industry.', 'sprite.'],
  },
  {
    forSurface: 'Seasonal palette swaps on the realm and county maps',
    keyPrefixes: [
      'terrain.forest.',
      'terrain.hills.',
      'terrain.chokepoint.',
      'tile.ground.',
      'tile.forest.',
      'tile.mountain.',
      'tile.water.',
    ],
  },
  {
    forSurface: 'Castle build screen — the two tiers the county spec added',
    keyPrefixes: ['castle.woodenPalisade', 'castle.stoneCastle'],
  },
  {
    forSurface: 'Faction-specific unit variants (generic sprites are the fallback)',
    keyPrefixes: ['unit.militia.', 'unit.knights.'],
  },
];

/** True when a pending key is accounted for by a named planned surface. */
export const isPlanned = (key: string): boolean =>
  PLANNED_ART.some((p) => p.keyPrefixes.some((prefix) => key.startsWith(prefix)));
